update gh-action file

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -61,17 +61,27 @@ jobs:
         # Install required compilers using Chocolatey
         choco install ${{ matrix.name }} libopencv-dev
         # --version ${{ matrix.version }}
-    
-        # Download and extract FFTW3 for Windows (64-bit)
+
+        # Download and extract FFTW3 for Windows (64-bit) from GitHub
         echo "Downloading FFTW3 for Windows..."
-        Invoke-WebRequest -Uri "https://sourceforge.net/projects/fftw3w32/files/fftw-3.3.8-dll64.zip/download" -OutFile "$env:Temp\fftw3.zip"
+        Invoke-WebRequest -Uri "https://github.com/fftw3/fftw3-windows/releases/download/v3.3.8/fftw-3.3.8-dll64.zip" -OutFile "$env:Temp\fftw3.zip"
+    
+        # Check if the download was successful
+        if (-Not (Test-Path "$env:Temp\fftw3.zip")) {
+        Write-Error "FFTW3 download failed!"
+        exit 1
+        }
+
+        # Extract the zip file
         Expand-Archive -Path "$env:Temp\fftw3.zip" -DestinationPath "$env:Temp\fftw3"
 
         # Set up environment variables for FFTW3
         setx FFTW3_INCLUDE_DIR "$env:Temp\fftw3\include"
         setx FFTW3_LIBRARY_DIR "$env:Temp\fftw3\lib"
         setx FFTW3_LIBRARIES "$env:Temp\fftw3\lib\libfftw3-3.dll"
+
         echo "FFTW3 installed and environment variables set."
+
     - name: Install dependencies (Linux)
       if: runner.os == 'Linux'
       run: sudo apt-get install ${{ matrix.compiler }} libopencv-dev libfftw3-dev
